[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "test_pkg"
authors = [
    {name = "tad", email = "tad@gmail.com"},
]
description = "My package description"
version = "0.0.0"
